services:
  - type: web
    name: my-line-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: MASSAGE_LINE_CHANNEL_ACCESS_TOKEN
        sync: false
